# Generated by Django 5.0.1 on 2024-01-11 21:43

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Projetos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dados', models.TextField()),
                ('nome_projeto', models.TextField()),
                ('criacao', models.DateTimeField(default=django.utils.timezone.now)),
                ('id_criador', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='ProjetosUsuarios',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.projetos')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
