# Generated by Django 3.2.16 on 2024-01-25 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projetos',
            name='descricao',
            field=models.TextField(default=''),
        ),
    ]
