# Generated by Django 3.2.16 on 2024-01-11 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projetos',
            name='id_criador',
            field=models.IntegerField(default=1),
        ),
    ]
