# Generated by Django 3.2.16 on 2024-01-11 11:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_projetos_id_criador'),
    ]

    operations = [
        migrations.AddField(
            model_name='projetos',
            name='criacao',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
